/*
 * board.c
 *
 *  Created on: 5 janv. 2022
 *      Author: kobeisch
 */


#include "config.h"
#include "board.h"
#include "macro_types.h"

void  BOARD_Init(){
	//Init des leds
	BSP_GPIO_PinCfg(GPIO_LED_YELLOW, PIN_LED_YELLOW, GPIO_MODE_OUTPUT_PP,GPIO_NOPULL,GPIO_SPEED_FREQ_HIGH);
	BSP_GPIO_PinCfg(GPIO_LED_RED, PIN_LED_RED, GPIO_MODE_OUTPUT_PP,GPIO_NOPULL,GPIO_SPEED_FREQ_HIGH);
	HAL_GPIO_WritePin(GPIO_LED_RED, PIN_LED_RED, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(GPIO_LED_YELLOW, PIN_LED_YELLOW, GPIO_PIN_RESET);

	//init des boutons
	BSP_GPIO_PinCfg(GPIO_BUTTON_LEFT, PIN_BUTTON_LEFT, GPIO_MODE_INPUT,GPIO_PULLUP,GPIO_SPEED_FREQ_HIGH);
	BSP_GPIO_PinCfg(GPIO_BUTTON_RIGHT, PIN_BUTTON_RIGHT, GPIO_MODE_INPUT,GPIO_PULLUP,GPIO_SPEED_FREQ_HIGH);
	BSP_GPIO_PinCfg(GPIO_BUTTON_VALIDATE, PIN_BUTTON_VALIDATE, GPIO_MODE_INPUT,GPIO_PULLUP,GPIO_SPEED_FREQ_HIGH);
}



